spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: chatting
      enable-auto-commit: true
      auto-offset-reset: earliest
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer